### ISSUE TITLE
Problem with a different Node.js version

### ISSUE THREAD

**Issue by xgalen** [bnoordhuis/node-heapdump#109]
Hi all!

I'm using `node 8.1.4` and when trying to use this module I've got this error:

```
/home/ubuntu/****/node_modules/heapdump/lib/main.js:18
  if (e.code !== 'MODULE_NOT_FOUND') throw e;
                                     ^

Error: The module '/home/ubuntu/****/node_modules/heapdump/build/Release/addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/adserver/node_modules/heapdump/lib/main.js:16:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

I've tried with `npm rebuild`,  `npm install`, uninstall and reinstall, `node-gyp configure build`... but nothing works. Everytime the same message. Any hint?

A bit of help would be appreciated :)

**Comment by xgalen** [comment]
Forget this, sorry. My fault.
I was running the process with a different node's version installed on the machine.

**Comment by xgalen** [comment]
Forget this, sorry. My fault.
I was running the process with a different node's version installed on the machine.
