### ISSUE TITLE
Cannot open include file: 'nan.h': No such file or directory

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [bnoordhuis/node-heapdump#122]
See error log:

System: Windows 10
Node: 10.13.0
NPM: 6.4.1

I have installed windows-build-tools and can compile other native addons without an issue except this module.

I have already tried to:
 - reinstall the buildtools, 
 - install Windows 10 SDKs, 
 - tried version 8.9.4 of Node

Any idea why am I missing the nan.h file?

CLI output
```
$ npm i heapdump

> heapdump@0.3.10 install C:\Work\Tools\packages\node_modules\heapdump
> node-gyp rebuild


C:\Work\Tools\packages\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Users\ales.menzel\AppData\Roaming\nvm\v10.13.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\ales.menzel\AppData\Roaming\nvm\v10.13.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Work\Tools\packages\node_modules\heapdump\build\..\src\compat.h
C:\Work\Tools\packages\node_modules\heapdump\build\..\src\compat-inl.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  heapdump.cc
c:\work\tools\packages\node_modules\heapdump\src\heapdump.cc(17): fatal error C1083: Cannot open include file: 'nan.h': No such file or directory [C:\Work\Tools\packages\node_modules\heapdump\build\addon.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ales.menzel\AppData\Roaming\nvm\v10.13.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ales.menzel\\AppData\\Roaming\\nvm\\v10.13.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Work\Tools\packages\node_modules\heapdump
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Work\Tools\packages\package.json'
npm WARN packages No description
npm WARN packages No repository field.
npm WARN packages No README data
npm WARN packages No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heapdump@0.3.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ales.menzel\AppData\Roaming\npm-cache\_logs\2018-11-01T13_59_56_115Z-debug.log
```

**Comment by alesmenzelsocialbakers** [comment]
**The issue is caused by the latest release 0.3.10**, version 0.3.9 can be installed without any issues.

**Comment by bnoordhuis** [comment]
Thanks for the bug report and the pull request. I had a fix ready for this (got a similar report today over email) but I hadn't been able to push it out until now.
