### ISSUE TITLE
Does not work with latest node.js v12 LTS

### ISSUE THREAD

**Issue by brandonros** [bnoordhuis/node-heapdump#138]
```
/app/node_modules/heapdump/index.js:18
  if (e.code !== 'MODULE_NOT_FOUND') throw e;
                                     ^

Error: Error relocating /app/node_modules/heapdump/build/Release/addon.node: _ZN2v88internal35IsolateFromNeverReadOnlySpaceObjectEm: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/heapdump/index.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by bnoordhuis** [comment]
That error almost certainly means it was compiled against a different version of Node.js than the one you're trying to use it with. Can you `rm -fr node_modules/ && npm install`?

**Comment by brandonros** [comment]
You're probably right, but I switched to `v8.getHeapSnapshot()` just in case. Thanks!
