### ISSUE TITLE
Fails to install on Windows

### ISSUE THREAD

**Issue by jaylagorio** [bnoordhuis/node-heapdump#139]
I'm a user of the Nightscout app (https://github.com/nightscout/cgm-remote-monitor/) which takes a dependency on `heapdump`. On Windows Server 2019 when I attempt to run `npm install` on that Node app with Node v10.15.2 and NPM v6.4.1 I get the following failure. The log file referred to at the end is attached here [2019-11-16T01_12_51_131Z-debug.log](https://github.com/bnoordhuis/node-heapdump/files/3853667/2019-11-16T01_12_51_131Z-debug.log). Although I don't control the direction of that project, it's pretty important to me that this builds on Windows Server.
)

```
C:\Nightscout125dev\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Nightscout125dev\node_modules\heapdump\build\..\src\compat-inl.h
C:\Nightscout125dev\node_modules\heapdump\build\..\src\compat.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  heapdump.cc
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(2570): error C2144: syntax error : 'int' should be p
receded by ';' [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(2570): error C4430: missing type specifier - int ass
umed. Note: C++ does not support default-int [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4273): error C2610: 'v8::WasmCompiledModule::Transfe
rrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function w
hich can be defaulted [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4276): error C2610: 'v8::WasmCompiledModule::Transfe
rrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)'
: is not a special member function which can be defaulted [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxpro
j]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4362): error C2610: 'v8::WasmModuleObjectBuilderStre
aming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function wh
ich can be defaulted [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4367): error C2610: 'v8::WasmModuleObjectBuilderStre
aming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special me
mber function which can be defaulted [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4632): error C2146: syntax error : missing ';' befor
e identifier 'size_t' [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4632): error C4430: missing type specifier - int ass
umed. Note: C++ does not support default-int [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h
': No such file or directory [C:\Nightscout125dev\node_modules\heapdump\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Nightscout125dev\node_modules\heapdump
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heapdump@0.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-11-16T01_12_51_131Z-debug.log
```

**Comment by bnoordhuis** [comment]
By the looks of it you have Visual Studio 2013 installed (msbuild 12.0) and that won't work if you want to build against Node.js v10.x. That's not a limitation of node-heapdump - newer versions of Node.js need newer versions of Visual Studio. Try upgrading to VS 2015.

**Comment by jaylagorio** [comment]
Wow - thank you for recognizing what others could not. I was definitely building with VS 2013 installed, installing VS 2015 and using `--msvs_version=2015` did the trick. Thank you so much!
