### ISSUE TITLE
module did not self-register on Apple M1 Pro

### ISSUE THREAD

**Issue by happy15** [bnoordhuis/node-heapdump#163]
Hi there, I tried to use heapdump on my new mbp with m1 pro chip, but got following error:
```
events.js:291
      throw er; // Unhandled 'error' event
      ^
Error: Module did not self-register: '/path/to/node_modules/heapdump/build/Release/addon.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/sheng/play/js/node_modules/heapdump/index.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (internal/worker.js:251:10)
    at Worker.[kOnMessage] (internal/worker.js:262:37)
    at MessagePort.<anonymous> (internal/worker.js:171:57)
    at MessagePort.emit (events.js:314:20)
    at MessagePort.onmessage (internal/worker/io.js:80:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
```
I googled around and couldn't solve it, any guide on this?

Thanks in advance.

**Comment by bnoordhuis** [comment]
It probably means one of two things:

1. The module failed to compile (it's native code, C++.) Look for error messages when you `npm install heapdump`.

2. You're trying to load it in a worker thread. node-heapdump only works with the "main" JS thread.

**Comment by happy15** [comment]
Thanks for the reply.

I was planning to dump the heap for analysis when main thread stucks and infinite gc happens. Since you point out that heapdump only works with the main thread, any alternative approach suggested?

**Comment by bnoordhuis** [comment]
Have a look at the `getHeapSnapshot()` method of node's builtin `v8` and `worker_threads` modules.

**Comment by happy15** [comment]
Thanks. Tried `v8.writeHeapSnapshot()` on worker thread and it only saved snapshot related to worker. It seems there is no way to dump heap snapshot for main thread while the main thread is busy and stuck?

**Comment by bnoordhuis** [comment]
If you mean when it's stuck in a busy loop, then no. You could try [llnode](https://github.com/nodejs/llnode).
