### ISSUE TITLE
error heapdump on windows

### ISSUE THREAD

**Issue by jscida** [bnoordhuis/node-heapdump#65]
Hi, I'm trying to install heapdump on windows server 2008 r2 standard x64 and i get an error, I believe i need to install visual studio, but i can not install visual studio on the server, i can install sdk though, so what are the required compilers/dependencies for this to work?
This is the error description:
```
C:\Chat-server-staging>npm install
npm http GET https://registry.npmjs.org/heapdump/0.3.3
npm http 200 https://registry.npmjs.org/heapdump/0.3.3
npm http GET https://registry.npmjs.org/heapdump/-/heapdump-0.3.3.tgz
npm http 200 https://registry.npmjs.org/heapdump/-/heapdump-0.3.3.tgz

> heapdump@0.3.3 install C:\Chat-server-staging\node_modules\heapdump
> node-gyp rebuild


C:\Chat-server-staging\node_modules\heapdump>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebui
ld
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
 TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Chat-server-staging\node_modules\heapdump\build\addon.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(146,5): error : Required file "" is missing. [C:\Chat-server-staging\
node_modules\heapdump\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Chat-server-staging\node_modules\heapdump
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! heapdump@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.3 install script.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Chat-server-staging
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Chat-server-staging\npm-debug.log
npm ERR! not ok code 0
```

**Comment by bnoordhuis** [comment]
Sorry, seems I missed the notification for this issue.  You can try installing an older version of the Windows SDK, newer versions don't ship with a C++ compiler anymore.  Hope that helps.
