### ISSUE TITLE
Error: Snapshot token not found

### ISSUE THREAD

**Issue by jaydeep17** [bnoordhuis/node-heapdump#67]
When I try to load the heapsnapshot in chrome dev tools it shows me the below error

```js
An error occurred when a call to method 'write' was requested
Error: Snapshot token not found
    at Object.WebInspector.HeapSnapshotLoader.write (chrome-devtools://devtools/bundled/heap_snapshot_worker_module.js:770:7)
    at Object.WebInspector.HeapSnapshotWorkerDispatcher.dispatchMessage (chrome-devtools://devtools/bundled/heap_snapshot_worker_module.js:815:95)
An error occurred when a call to method 'close' was requested
SyntaxError: Unexpected token
    at Object.parse (native)
    at Object.WebInspector.HeapSnapshotLoader._parseStringsArray (chrome-devtools://devtools/bundled/heap_snapshot_worker_module.js:767:117)
    at Object.WebInspector.HeapSnapshotLoader.close (chrome-devtools://devtools/bundled/heap_snapshot_worker_module.js:756:6)
    at Object.WebInspector.HeapSnapshotWorkerDispatcher.dispatchMessage (chrome-devtools://devtools/bundled/heap_snapshot_worker_module.js:815:95)
```

I have a snashot of about 15MB.

Using Node v0.12.7 inside Docker.
Google Chrome v45.0.2454.85 (64-bit)

**Comment by jaydeep17** [comment]
Never mind, it was my mistake!

**Comment by a3gis** [comment]
What was the issue @jaydeep17 ?

**Comment by jaydeep17** [comment]
Sorry @a3gis but it's been about a year since this issue, and I no longer remember 😕
