### ISSUE TITLE
Installation errors on Centos 6.7

### ISSUE THREAD

**Issue by codecowboy** [bnoordhuis/node-heapdump#77]
I'm trying to install NodeBB which has heapdump as a dependency but get the following error:

gcc version is ```g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)```
```
npm install
|
> heapdump@0.3.7 install /vagrant/nodebb/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/vagrant/nodebb/node_modules/heapdump/build'
make: Warning: File `addon.target.mk' has modification time 0.29 s in the future
  CXX(target) Release/obj.target/addon/src/heapdump.o
In file included from /home/vagrant/.node-gyp/4.2.4/include/node/node.h:42,
                 from ../src/heapdump.cc:15:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: At global scope:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:790: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:815: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:827: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: At global scope:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:852: error: expected unqualified-id before ‘using’
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:1089: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:1095: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:3205: error: ‘nullptr’ was not declared in this scope
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/vagrant/.node-gyp/4.2.4/include/node/v8.h:7164: error: ‘nullptr’ was not declared in this scope
../src/heapdump.cc: At global scope:
../src/heapdump.cc:52: error: ‘v8::Handle’ has not been declared
make: *** [Release/obj.target/addon/src/heapdump.o] Error 1
make: Leaving directory `/vagrant/nodebb/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.el6.x86_64
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.2.4/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/nodebb/node_modules/heapdump
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.32-573.el6.x86_64
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.2.4/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.4/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/nodebb/npm-debug.log

```

**Comment by bnoordhuis** [comment]
You need g++ 4.8 or clang++ 3.4 or newer.  That's not unique to node-heapdump by the way, it's because node v4 requires C++11 support.  Hope that helps.

**Comment by codecowboy** [comment]
thanks
