### ISSUE TITLE
Crashes sometimes, node 5.6.0

### ISSUE THREAD

**Issue by Zarel** [bnoordhuis/node-heapdump#79]
I haven't been able to reproduce the precise conditions it crashes, but I assume it has to do with how much memory node is using.

    error: Forever detected script was killed by signal: SIGSEGV

There doesn't appear to be any error message.

This is on https://github.com/Zarel/Pokemon-Showdown

I run two servers, one gets around 10,000 concurrent users, one gets around 100.

The big one pretty much always crashes whenever I try to heap dump. `top` reports ~2.4GB VIRT, ~1.5GB RES for that one. The one time I was able to get a heapdump that didn't crash, it was a 200 MB heap, so something weird may be going on.

The small one has never crashed when I try to heap dump, and its heap dumps are around 50 MB.

**Comment by bnoordhuis** [comment]
Do you see something in the system logs (i.e. `dmesg`) after it segfaults?  What does `ulimit -a` print for the user and/or shell you run Pokemon Showdown as?

**Comment by Zarel** [comment]
the last few lines of `dmesg` include:

```
[36705518.372457] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952084489:952084715 (repaired)
[36705518.971517] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952084489:952084715 (repaired)
[36705522.062673] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952089720:952089879 (repaired)
[36705522.653742] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952089720:952089879 (repaired)
[36705526.611535] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952095211:952095282 (repaired)
[36705530.777004] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952099622:952099778 (repaired)
[36705531.376066] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952099622:952099778 (repaired)
[36705571.620952] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952138752:952138823 (repaired)
[36705596.645705] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 952226500:952226683 (repaired)
[36705807.411183] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 953054207:953054439 (repaired)
[36705815.746110] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 953091346:953091527 (repaired)
[36705866.606350] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 953260850:953260920 (repaired)
[36705867.205412] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 953260850:953260920 (repaired)
[36705869.809329] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 953273787:953273976 (repaired)
[36705870.408387] Peer 67.142.58.198:2845/8043 unexpectedly shrunk window 953273787:953273976 (repaired)
[36765644.055333] traps: node[29123] general protection ip:e0806a sp:7ffff19e26b0 error:0 in node[400000+13c7000]
```

I think `67.142.58.198` may be a DoS attacker; the IP looks familiar.

```
$ ulimit -a
Maximum size of core files created                           (kB, -c) unlimited
Maximum size of a process’s data segment                     (kB, -d) unlimited
Maximum size of files created by the shell                   (kB, -f) unlimited
Maximum size that may be locked into memory                  (kB, -l) 64
Maximum resident set size                                    (kB, -m) unlimited
Maximum number of open file descriptors                          (-n) 32768
Maximum stack size                                           (kB, -s) 8192
Maximum amount of cpu time in seconds                   (seconds, -t) unlimited
Maximum number of processes available to a single user           (-u) 515015
Maximum amount of virtual memory available to the shell      (kB, -v) unlimited
```

**Comment by Zarel** [comment]
If it's relevant, the server has 64 GB of RAM.

**Comment by bnoordhuis** [comment]
It's possible the stack size (`ulimit -s`) is the culprit.  Can you try raising it to something really high, say 32 or 64 MB?  If that doesn't fix it, can you try grabbing a backtrace with gdb or catchsegv?

**Comment by Zarel** [comment]
I'll do that later today and report back.

**Comment by Zarel** [comment]
I've set the stack limit to 64 MB and it still crashed (right after the server restarted, too). Will try gdb when I get the chance.

**Comment by Zarel** [comment]
Hey, it didn't crash the first time!

Second time:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000d74dfa in node::WrapperInfo(unsigned short, v8::Local<v8::Value>)
    ()
(gdb) bt full
#0  0x0000000000d74dfa in node::WrapperInfo(unsigned short, v8::Local<v8::Value>) ()
No symbol table info available.
#1  0x0000000000a1f740 in v8::internal::HeapProfiler::ExecuteWrapperClassCallback(unsigned short, v8::internal::Object**) ()
No symbol table info available.
#2  0x0000000000a31140 in v8::internal::GlobalHandlesExtractor::VisitEmbedderReference(v8::internal::Object**, unsigned short) ()
No symbol table info available.
#3  0x0000000000a1cccc in v8::internal::GlobalHandles::IterateAllRootsWithClassIds(v8::internal::ObjectVisitor*) ()
No symbol table info available.
#4  0x0000000000a2c7b0 in v8::internal::NativeObjectsExplorer::FillRetainedObjects() [clone .part.551] ()
No symbol table info available.
#5  0x0000000000a32865 in v8::internal::NativeObjectsExplorer::IterateAndExtractReferences(v8::internal::SnapshotFiller*) ()
No symbol table info available.
#6  0x0000000000a329f8 in v8::internal::HeapSnapshotGenerator::GenerateSnapshot() ()
No symbol table info available.
#7  0x0000000000a1fb8c in v8::internal::HeapProfiler::TakeSnapshot(v8::ActivityControl*, v8::HeapProfiler::ObjectNameResolver*) ()
No symbol table info available.
#8  0x00007f60c2ac61fe in (anonymous namespace)::WriteSnapshot(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/ps/showdown/node_modules/heapdump/build/Release/addon.node
No symbol table info available.
#9  0x000000000087e182 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
No symbol table info available.
#10 0x00000000008a8641 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>&)
    ()
No symbol table info available.
#11 0x00000000008a8b32 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
No symbol table info available.
#12 0x00002cc0b350839b in ?? ()
No symbol table info available.
#13 0x00007fff1d91f0e0 in ?? ()
No symbol table info available.
#14 0x00002cc0b35082e1 in ?? ()
No symbol table info available.
#15 0x00007fff1d91f170 in ?? ()
No symbol table info available.
#16 0x00007fff1d91f1d8 in ?? ()
No symbol table info available.
#17 0x00002cc0b3531918 in ?? ()
No symbol table info available.
#18 0x000023da93c44e41 in ?? ()
No symbol table info available.
#19 0x00003d5e3c90ab91 in ?? ()
No symbol table info available.
#20 0x0000000000000000 in ?? ()
No symbol table info available.
```

It seems to crash around 90% of the time.

**Comment by bnoordhuis** [comment]
Does `find node_modules/ -name \*.node` find anything besides heapdump.node?  The crash originates from node core (src/async-wrap.cc to be exact), which could either mean it's a core bug or that another add-on is stamping on memory.

**Comment by Zarel** [comment]
```
$ find node_modules/ -name \*.node
node_modules/heapdump/build/Release/obj.target/addon.node
node_modules/heapdump/build/Release/addon.node
```

**Comment by bnoordhuis** [comment]
Okay, that's something.  Is there a possibility you can try a node debug build?  `./configure && make -C out BUILDTYPE=Debug` will build `out/Debug/node`.

**Comment by Zarel** [comment]
I can't reproduce this anymore.

I think the problem had something to do with renaming my old `node_modules` folder for a different version to `node_modules_old` instead of deleting it.
