### ISSUE TITLE
Does not install on CentOS 6.3

### ISSUE THREAD

**Issue by franza** [bnoordhuis/node-heapdump#82]
I'm trying to install `heapdump` on CentOS 6.3 with NodeJS 4.4.0 (installed with `nvm`) and getting this error:

```
[root@tablet2 ~]$ npm install -g heapdump
-
> heapdump@0.3.7 install /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdu                                                                                                                                                             mp
> node-gyp rebuild

sh: node-gyp: command not found
npm ERR! Linux 2.6.32-279.2.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.4.0/bin/node" "/root/.nvm/versions/no                                                                                                                                                             de/v4.4.0/bin/npm" "install" "-g" "heapdump"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

When I am installing this locally (without `-g`) I am getting different error:

```
[root@tablet2 ~]$ npm install heapdump
-
> heapdump@0.3.7 install /root/node_modules/heapdump
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/root/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
In file included from /root/.node-gyp/4.4.0/include/node/node.h:42,
                 from ../src/heapdump.cc:15:
/root/.node-gyp/4.4.0/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/root/.node-gyp/4.4.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/4.4.0/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/4.4.0/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/4.4.0/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/4.4.0/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: At global scope:
/root/.node-gyp/4.4.0/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/root/.node-gyp/4.4.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/4.4.0/include/node/v8.h:790: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/4.4.0/include/node/v8.h:815: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/4.4.0/include/node/v8.h:827: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: At global scope:
/root/.node-gyp/4.4.0/include/node/v8.h:852: error: expected unqualified-id before ‘using’
/root/.node-gyp/4.4.0/include/node/v8.h:1089: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h:1095: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/4.4.0/include/node/v8.h:3205: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.4.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/4.4.0/include/node/v8.h:7164: error: ‘nullptr’ was not declared in this scope
../src/heapdump.cc: At global scope:
../src/heapdump.cc:52: error: ‘v8::Handle’ has not been declared
make: *** [Release/obj.target/addon/src/heapdump.o] Error 1
make: Leaving directory `/root/node_modules/heapdump/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v4.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-279.2.1.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v4.4.0/bin/node" "/root/.nvm/versions/node/v4.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/heapdump
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm ERR! Linux 2.6.32-279.2.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.4.0/bin/node" "/root/.nvm/versions/node/v4.4.0/bin/npm" "install" "heapdump"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

**Comment by bnoordhuis** [comment]
The first error (`sh: node-gyp: command not found`) is what it says, you need to have node-gyp on your path.  It's bundled with node and npm.

The second error is because your compiler doesn't understand C++11.  You need to use g++ 4.8 or clang++ 3.4 or newer.

**Comment by franza** [comment]
Thanks for the answer. Regarding the first error `sh: node-gyp: command not found`: I installed node-gyp explicitly and globally and there is still same error:

```
[root@tablet2 ~]$ npm i -g node-gyp
/root/.nvm/versions/node/v4.4.0/bin/node-gyp -> /root/.nvm/versions/node/v4.4.0/lib/node_modules/node-gyp/bin/node-gyp.js
node-gyp@3.3.1 /root/.nvm/versions/node/v4.4.0/lib/node_modules/node-gyp
├── graceful-fs@4.1.3
├── semver@5.1.0
├── osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
├── nopt@3.0.6 (abbrev@1.0.7)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.3)
├── fstream@1.0.8 (inherits@2.0.1)
├── which@1.2.4 (isexe@1.1.2, is-absolute@0.1.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.8)
├── rimraf@2.5.2 (glob@7.0.3)
├── npmlog@2.0.3 (ansi@0.3.1, gauge@1.2.7, are-we-there-yet@1.1.2)
├── request@2.69.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.0.2, combined-stream@1.0.5, mime-types@2.1.10, form-data@1.0.0-rc4, aws4@1.3.2, bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
└── path-array@1.0.1 (array-index@1.0.0)
[root@tablet2 ~]$ npm i -g heapdump
-
> heapdump@0.3.7 install /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
> node-gyp rebuild

sh: node-gyp: command not found
npm ERR! Linux 2.6.32-279.2.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.4.0/bin/node" "/root/.nvm/versions/node/v4.4.0/bin/npm" "i" "-g" "heapdump"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
[root@tablet2 ~]$ node-gyp

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `make` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates a Makefile for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@3.3.1  /root/.nvm/versions/node/v4.4.0/lib/node_modules/node-gyp
node@4.4.0
```

**Comment by bnoordhuis** [comment]
I'm going to guess it's because `/root/.nvm/versions/node/v4.4.0/bin` is not part of your PATH environment variable.

**Comment by franza** [comment]
Looks like I have it:

```
[root@tablet2 ~]$ echo $PATH
/root/.nvm/versions/node/v4.4.0/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

**Comment by bnoordhuis** [comment]
It's possible you need to pass `--unsafe-perms` to npm because you're running as root.

**Comment by franza** [comment]
The error is still the same. Here's the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v4.4.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v4.4.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'heapdump' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose install initial load of /root/.nvm/versions/node/v4.4.0/lib/package.json
5 verbose readDependencies loading dependencies from /root/.nvm/versions/node/v4.4.0/lib/package.json
6 silly cache add args [ 'heapdump', null ]
7 verbose cache add spec heapdump
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'heapdump',
8 silly cache add   scope: null,
8 silly cache add   name: 'heapdump',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed heapdump@latest
10 verbose addNamed "latest" is being treated as a dist-tag for heapdump
11 info addNameTag [ 'heapdump', 'latest' ]
12 silly mapToRegistry name heapdump
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/heapdump
16 verbose addNameTag registry:https://registry.npmjs.org/heapdump not in flight; fetching
17 verbose request uri https://registry.npmjs.org/heapdump
18 verbose request no auth needed
19 info attempt registry request try #1 at 6:16:09 AM
20 verbose request id 25c1fa97801fee2d
21 verbose etag "3T7MZLV027SGAXFJ9S4J408NP"
22 http request GET https://registry.npmjs.org/heapdump
23 http 304 https://registry.npmjs.org/heapdump
24 verbose headers { date: 'Thu, 24 Mar 2016 10:16:09 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   'cache-control': 'max-age=300',
24 verbose headers   etag: '"3T7MZLV027SGAXFJ9S4J408NP"',
24 verbose headers   age: '70',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-atl6243-ATL',
24 verbose headers   'x-cache': 'HIT',
24 verbose headers   'x-cache-hits': '1',
24 verbose headers   'x-timer': 'S1458814569.897412,VS0,VE0',
24 verbose headers   vary: 'Accept' }
25 silly get cb [ 304,
25 silly get   { date: 'Thu, 24 Mar 2016 10:16:09 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=300',
25 silly get     etag: '"3T7MZLV027SGAXFJ9S4J408NP"',
25 silly get     age: '70',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-atl6243-ATL',
25 silly get     'x-cache': 'HIT',
25 silly get     'x-cache-hits': '1',
25 silly get     'x-timer': 'S1458814569.897412,VS0,VE0',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/heapdump from cache
27 verbose get saving heapdump to /root/.npm/registry.npmjs.org/heapdump/.cache.json
28 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
29 silly addNameTag next cb for heapdump with tag latest
30 silly addNamed heapdump@0.3.7
31 verbose addNamed "0.3.7" is a plain semver version for heapdump
32 silly cache afterAdd heapdump@0.3.7
33 verbose afterAdd /root/.npm/heapdump/0.3.7/package/package.json not in flight; writing
34 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
35 verbose afterAdd /root/.npm/heapdump/0.3.7/package/package.json written
36 silly install resolved [ { name: 'heapdump',
36 silly install resolved     main: './lib/main',
36 silly install resolved     version: '0.3.7',
36 silly install resolved     description: 'Make a dump of the V8 heap for later inspection.',
36 silly install resolved     homepage: 'https://github.com/bnoordhuis/node-heapdump',
36 silly install resolved     author:
36 silly install resolved      { name: 'Ben Noordhuis',
36 silly install resolved        email: 'info@bnoordhuis.nl',
36 silly install resolved        url: 'http://bnoordhuis.nl/' },
36 silly install resolved     repository:
36 silly install resolved      { type: 'git',
36 silly install resolved        url: 'git://github.com/bnoordhuis/node-heapdump.git' },
36 silly install resolved     engines: { node: '>=0.10.0' },
36 silly install resolved     license: 'ISC',
36 silly install resolved     scripts: { test: 'tap test/test-*', install: 'node-gyp rebuild' },
36 silly install resolved     devDependencies: { shelljs: '~0.3.0', tap: '~0.4.12' },
36 silly install resolved     gypfile: true,
36 silly install resolved     gitHead: '3e308b302fb2d7beba5b1c4a6eaf92caba51cbf2',
36 silly install resolved     bugs: { url: 'https://github.com/bnoordhuis/node-heapdump/issues' },
36 silly install resolved     _id: 'heapdump@0.3.7',
36 silly install resolved     _shasum: 'f50df2b140e5cde7656638f4c384d683b0143298',
36 silly install resolved     _from: 'heapdump@latest',
36 silly install resolved     _npmVersion: '2.13.3',
36 silly install resolved     _nodeVersion: '3.0.1-pre',
36 silly install resolved     _npmUser: { name: 'bnoordhuis', email: 'info@bnoordhuis.nl' },
36 silly install resolved     maintainers: [ [Object] ],
36 silly install resolved     dist:
36 silly install resolved      { shasum: 'f50df2b140e5cde7656638f4c384d683b0143298',
36 silly install resolved        tarball: 'http://registry.npmjs.org/heapdump/-/heapdump-0.3.7.tgz' },
36 silly install resolved     directories: {},
36 silly install resolved     _resolved: 'https://registry.npmjs.org/heapdump/-/heapdump-0.3.7.tgz',
36 silly install resolved     readme: 'ERROR: No README data found!' } ]
37 info install heapdump@0.3.7 into /root/.nvm/versions/node/v4.4.0/lib
38 info installOne heapdump@0.3.7
39 verbose installOne of heapdump to /root/.nvm/versions/node/v4.4.0/lib not in flight; installing
40 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
41 verbose lock using /root/.npm/_locks/heapdump-124d02f95a1a4097.lock for /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
42 silly install write writing heapdump 0.3.7 to /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
43 verbose unbuild lib/node_modules/heapdump
44 silly gentlyRm /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump is being purged from base /root/.nvm/versions/node/v4.4.0
45 verbose gentlyRm don't care about contents; nuking /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
46 verbose tar unpack /root/.npm/heapdump/0.3.7/package.tgz
47 verbose tar unpacking to /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
48 silly gentlyRm /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump is being purged
49 verbose gentlyRm don't care about contents; nuking /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
50 silly gunzTarPerm modes [ '755', '644' ]
51 silly gunzTarPerm extractEntry package.json
52 silly gunzTarPerm modified mode [ 'package.json', 436, 420 ]
53 silly gunzTarPerm extractEntry .npmignore
54 silly gunzTarPerm modified mode [ '.npmignore', 436, 420 ]
55 silly gunzTarPerm extractEntry README.md
56 silly gunzTarPerm modified mode [ 'README.md', 436, 420 ]
57 silly gunzTarPerm extractEntry LICENSE
58 silly gunzTarPerm modified mode [ 'LICENSE', 436, 420 ]
59 silly gunzTarPerm extractEntry .clang-format
60 silly gunzTarPerm modified mode [ '.clang-format', 436, 420 ]
61 silly gunzTarPerm extractEntry binding.gyp
62 silly gunzTarPerm modified mode [ 'binding.gyp', 436, 420 ]
63 silly gunzTarPerm extractEntry lib/main.js
64 silly gunzTarPerm modified mode [ 'lib/main.js', 436, 420 ]
65 silly gunzTarPerm extractEntry src/compat-inl.h
66 silly gunzTarPerm modified mode [ 'src/compat-inl.h', 436, 420 ]
67 silly gunzTarPerm extractEntry src/compat.h
68 silly gunzTarPerm modified mode [ 'src/compat.h', 436, 420 ]
69 silly gunzTarPerm extractEntry src/heapdump-posix.h
70 silly gunzTarPerm modified mode [ 'src/heapdump-posix.h', 436, 420 ]
71 silly gunzTarPerm extractEntry src/heapdump-win32.h
72 silly gunzTarPerm modified mode [ 'src/heapdump-win32.h', 436, 420 ]
73 silly gunzTarPerm extractEntry src/heapdump.cc
74 silly gunzTarPerm modified mode [ 'src/heapdump.cc', 436, 420 ]
75 silly gunzTarPerm extractEntry test/test-callback-without-filename.js
76 silly gunzTarPerm modified mode [ 'test/test-callback-without-filename.js', 436, 420 ]
77 silly gunzTarPerm extractEntry test/test-callback.js
78 silly gunzTarPerm modified mode [ 'test/test-callback.js', 436, 420 ]
79 silly gunzTarPerm extractEntry test/test-sigusr2.js
80 silly gunzTarPerm modified mode [ 'test/test-sigusr2.js', 436, 420 ]
81 verbose write writing to /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump/package.json
82 info preinstall heapdump@0.3.7
83 verbose readDependencies loading dependencies from /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump/package.json
84 verbose readDependencies loading dependencies from /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump/package.json
85 silly install resolved []
86 verbose about to build /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
87 info build /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
88 info linkStuff heapdump@0.3.7
89 silly linkStuff heapdump@0.3.7 has /root/.nvm/versions/node/v4.4.0/lib/node_modules as its parent node_modules
90 silly linkStuff heapdump@0.3.7 is part of a global install
91 silly linkStuff heapdump@0.3.7 is installed into a global node_modules
92 silly linkStuff heapdump@0.3.7 is installed into the top-level global node_modules
93 verbose linkBins heapdump@0.3.7
94 verbose linkMans heapdump@0.3.7
95 verbose rebuildBundles heapdump@0.3.7
96 info install heapdump@0.3.7
97 verbose unsafe-perm in lifecycle false
98 info heapdump@0.3.7 Failed to exec install script
99 verbose unlock done using /root/.npm/_locks/heapdump-124d02f95a1a4097.lock for /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
100 verbose stack Error: heapdump@0.3.7 install: `node-gyp rebuild`
100 verbose stack spawn ENOENT
100 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v4.4.0/lib/node_modules/npm/lib/utils/spawn.js:17:16)
100 verbose stack     at emitTwo (events.js:87:13)
100 verbose stack     at ChildProcess.emit (events.js:172:7)
100 verbose stack     at maybeClose (internal/child_process.js:827:16)
100 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
101 verbose pkgid heapdump@0.3.7
102 verbose cwd /root
103 error Linux 2.6.32-279.2.1.el6.x86_64
104 error argv "/root/.nvm/versions/node/v4.4.0/bin/node" "/root/.nvm/versions/node/v4.4.0/bin/npm" "i" "-g" "heapdump"
105 error node v4.4.0
106 error npm  v2.14.20
107 error file sh
108 error code ELIFECYCLE
109 error errno ENOENT
110 error syscall spawn
111 error heapdump@0.3.7 install: `node-gyp rebuild`
111 error spawn ENOENT
112 error Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
112 error This is most likely a problem with the heapdump package,
112 error not with npm itself.
112 error Tell the author that this fails on your system:
112 error     node-gyp rebuild
112 error You can get information on how to open an issue for this project with:
112 error     npm bugs heapdump
112 error Or if that isn't available, you can get their info via:
112 error
112 error     npm owner ls heapdump
112 error There is likely additional logging output above.
113 verbose exit [ 1, true ]
114 verbose unbuild lib/node_modules/heapdump
115 info preuninstall heapdump@0.3.7
116 info uninstall heapdump@0.3.7
117 verbose unbuild rmStuff heapdump@0.3.7 from /root/.nvm/versions/node/v4.4.0/lib/node_modules
118 info postuninstall heapdump@0.3.7
119 silly gentlyRm /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump is being purged from base /root/.nvm/versions/node/v4.4.0
120 verbose gentlyRm don't care about contents; nuking /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
121 silly vacuum-fs purging /root/.nvm/versions/node/v4.4.0/lib/node_modules/heapdump
122 silly vacuum-fs quitting because other entries in /root/.nvm/versions/node/v4.4.0/lib/node_modules
```

Maybe this issue is connected to the fact that initially I had NodeJS v0.8.15 installed without `nvm`, and I never removed this version of NodeJS after I started to use `nvm`.

**Comment by bnoordhuis** [comment]
It's possible.  I can't really help you with that, I'm afraid; it's not an issue with node-heapdump

**Comment by franza** [comment]
Thanks for response. If I find how to fix it I will post it here, however I think that the issue can be closed now.
