### ISSUE TITLE
Can't build via npm: gyp failed with exit code 1

### ISSUE THREAD

**Issue by guymorita** [bnoordhuis/node-heapdump#93]
Hey guys,

Unable to properly configure heapdump because of node-gyp. I've searched far and wide for fixes and tried lots of stuff. Is there something I'm missing with how to configure node-gyp?
```
guys-mbp:benchmark_raccoon_movielens guymorita$ npm install --save-dev heapdump

> heapdump@0.3.7 install /Users/guymorita/Projects/benchmark_raccoon_movielens/node_modules/heapdump
> node-gyp rebuild

  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/addon.node
benchmark_raccoon_movielens@0.0.1 /Users/guymorita/Projects/benchmark_raccoon_movielens
└── heapdump@0.3.7

guys-mbp:benchmark_raccoon_movielens guymorita$ node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.3.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/guymorita/Projects/benchmark_raccoon_movielens/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/guymorita/.node-gyp/7.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/guymorita/.node-gyp/7.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/guymorita/Projects/benchmark_raccoon_movielens',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/guymorita/Projects/benchmark_raccoon_movielens) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/guymorita/Projects/benchmark_raccoon_movielens
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```
Here is my setup:
```
guys-mbp:benchmark_raccoon_movielens guymorita$ sw_vers -productVersion
10.10.5
guys-mbp:benchmark_raccoon_movielens guymorita$ node -v
v7.3.0
guys-mbp:benchmark_raccoon_movielens guymorita$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
I have already tried:
```
deleting dir ~/.node_gyp and running npm install
```
```
sudo npm install -g node-gyp@3.4.0
```
```
cd /usr/local/lib sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib 
```
```
brew install gcc
```
```
sudo npm cache clean -f
sudo npm install -g n
sudo n 4.4.5
sudo npm install npm -g
sudo npm uninstall node-gyp -g
```
Thanks!

**Comment by bnoordhuis** [comment]
What exactly are you trying to do?  `npm install heapdump` worked fine, didn't it?  It's when you run `node-gyp build` from the top-level directory that things go wrong, but there is no need to run it manually (and if you do, it should be run from `node_modules/heapdump` - but again, no need.)

**Comment by guymorita** [comment]
@bnoordhuis Gotcha. Going without the node-gyp configure build then. However I have a new error when trying to import:

``` bash
Guys-MacBook-Pro:benchmark_raccoon_movielens guymorita$ npm install heapdump
> heapdump@0.3.7 install /Users/guymorita/Projects/benchmark_raccoon_movielens/node_modules/heapdump
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/addon.node
benchmark_raccoon_movielens@0.0.1 /Users/guymorita/Projects/benchmark_raccoon_movielens
└── heapdump@0.3.7
```

``` js
require-hook.js:50 Uncaught Error: 
/Users/guymorita/Projects/benchmark_raccoon_movielens/test.js

/Users/guymorita/Projects/benchmark_raccoon_movielens/node_modules/heapdump/lib/main.js
Cannot find module '../build/Debug/addon'
```

**Comment by bnoordhuis** [comment]
I suspect you are building heapdump for version $x of node but trying to load it with version $y.  Try passing `--target=$y` to npm, e.g. `rm -rf node_modules/heapdump && npm install heapdump --target=7.3.0`.
