### ISSUE TITLE
Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by vatex** [bnoordhuis/node-heapdump#97]
Errored, while running: npm install heapdump
```
make: Entering directory `/home/valeri/projects/user/server/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
/home/valeri/projects/user/server/node_modules/.bin/touch: 1: /home/valeri/projects/user/server/node_modules/.bin/touch: Syntax error: "(" unexpected
make: *** [Release/obj.target/addon/src/heapdump.o] Error 2
make: Leaving directory `/home/valeri/projects/user/server/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/valeri/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-66-generic
gyp ERR! command "/home/valeri/.nvm/versions/node/v6.9.1/bin/node" "/home/valeri/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/valeri/projects/user/server/node_modules/heapdump
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/home/valeri/.nvm/versions/node/v6.9.1/bin/node" "/home/valeri/.nvm/versions/node/v6.9.1/bin/npm" "install" "heapdump"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/valeri/projects/user/server/npm-debug.log
```

**Comment by bnoordhuis** [comment]
That is a problem with your project, not heapdump.  Note the error:

> /home/valeri/projects/user/server/node_modules/.bin/touch: 1: /home/valeri/projects/user/server/node_modules/.bin/touch: Syntax error: "(" unexpected

One of your dependencies is (or depends on) [touch](https://www.npmjs.com/package/touch) and it interferes with the system's touch(1) that is used in the Makefile.
